// Mocks generated by Mockito 5.4.4 from annotations
// in code_challenge/test/photo/photo_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:code_challenge/data/local/photo_remote_data_source.dart' as _i2;
import 'package:code_challenge/data/repository/photo_repository_impl.dart'
    as _i3;
import 'package:code_challenge/models/photo_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePhotoRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.PhotoRemoteDataSource {
  _FakePhotoRemoteDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PhotoRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoRepositoryImpl extends _i1.Mock
    implements _i3.PhotoRepositoryImpl {
  MockPhotoRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PhotoRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakePhotoRemoteDataSource_0(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i2.PhotoRemoteDataSource);

  @override
  _i4.Future<List<_i5.PhotoModel>> getPhotos({
    required int? start,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPhotos,
          [],
          {
            #start: start,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i5.PhotoModel>>.value(<_i5.PhotoModel>[]),
      ) as _i4.Future<List<_i5.PhotoModel>>);
}

/// A class which mocks [PhotoRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoRemoteDataSource extends _i1.Mock
    implements _i2.PhotoRemoteDataSource {
  MockPhotoRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.PhotoModel>> getPhotos({
    required int? start,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPhotos,
          [],
          {
            #start: start,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i5.PhotoModel>>.value(<_i5.PhotoModel>[]),
      ) as _i4.Future<List<_i5.PhotoModel>>);
}
